# Site settings
title: herchila
# email: your-email@domain.com
description: shortbio.md
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://herchila.github.io" # the base hostname & protocol for your site
twitter_username: herchila
github_username:  herchila

# Build settings
markdown: kramdown
