# Site settings
title: herchila
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Inquieto, autodidacta, me aburro enseguida, geek, me gusta aprender cosas nuevas sobre desarrollo web. Amo hacer deporte y viajar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://herchila.github.io" # the base hostname & protocol for your site
twitter_username: herchila
github_username:  herchila

# Build settings
markdown: kramdown
